<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <NoWarn>CA1416</NoWarn>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Otp.NET" Version="1.4.0" />
    <PackageReference Include="Porta.Pty" Version="1.0.7" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="SharpCompress" Version="0.48.1" />
    <PackageReference Include="XTerm.NET" Version="1.0.15" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.7" />
  </ItemGroup>

</Project>
